services:
  db:
    container_name: db
    image: postgres:${POSTGRESQL_VERSION}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/DogData.csv:/data/DogData.csv
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web-server:
    container_name: web-server
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    environment:
      DB_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}"
